name: Backend CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run tests
        run: mvn test

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker gcr.io
          docker build -t gcr.io/receipt/${{ env.GCP_PROJECT }}/receipt-backend:${{ github.sha }} .
          docker push gcr.io/${{ env.GCP_PROJECT }}/receipt-backend:${{ github.sha }}
      - name: Deploy to Cloud Run (Stable Revision)
        run: |
          gcloud run deploy backend \
            --image gcr.io/${{ env.GCP_PROJECT }}/receipt-backend:${{ github.sha }} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --tag stable \
            --set-env-vars MONGODB_URI=${{ secrets.MONGODB_URI }},SPRING_PROFILES_ACTIVE=prod
      - name: Deploy to Cloud Run (Canary Revision)
        run: |
          gcloud run deploy backend \
            --image gcr.io/${{ env.GCP_PROJECT }}/receipt-backend:${{ github.sha }} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --tag canary \
            --set-env-vars MONGODB_URI=${{ secrets.MONGODB_URI }},SPRING_PROFILES_ACTIVE=prod
      - name: Traffic Splitting
        run: |
          gcloud run services update-traffic backend \
            --to-tags stable=90,canary=10 \
            --region us-central1
env:
  GCP_PROJECT: receipt-460023
